'$include:'Console/getCursor.bi'
'$include:'Console/getSize.bi'
'$include:'Console/newLine.bi'
'$include:'Console/read.bi'
'$include:'Console/setCursor.bi'
'$include:'Console/setSize.bi'
'$include:'Console/write.bi'
'$include:'Console/writeLine.bi'
